import "dotenv/config";
const q = async (url, query, variables) => {
  const r = await fetch(url, { method:"POST", headers:{"content-type":"application/json"}, body: JSON.stringify({query, variables}) });
  return r.json();
};
const IX = process.env.INDEXER_URL, PF = process.env.PRICE_FEED_URL;
const now = Math.floor(Date.now()/1000);
console.log("=== Market fields test ===");
let r = await q(IX, `query($venue:String!,$now:numeric!){ Market(where:{marketType:{_eq:"BINARY"},venueId:{_eq:$venue},strike:{_eq:"0"},expiry:{_gt:$now}}, order_by:{expiry:asc}, limit:3){ id poolAddress marketAddress asset question expiry tradingStart intervalSec yesTokenId noTokenId clobStatus oracleQuestionId cumulativeQuoteVolume tradeCount } }`, { venue: process.env.VENUE_ID, now: now+360 });
console.log(JSON.stringify(r).slice(0,700));
console.log("\n=== ReferenceLink + OracleAnswer ===");
const ids = (r.data?.Market ?? []).map(m=>m.id.toLowerCase());
let r2 = await q(IX, `query($ids:[String!]){ MarketReferenceLink(where:{market_id:{_in:$ids}}){ market_id referenceQuestionId } }`, { ids });
console.log(JSON.stringify(r2).slice(0,400));
const qids = (r2.data?.MarketReferenceLink ?? []).map(l=>l.referenceQuestionId);
let r3 = await q(IX, `query($qids:[String!]){ OracleAnswer(where:{oracleQuestionId:{_in:$qids}}){ oracleQuestionId numericValue } }`, { qids });
console.log(JSON.stringify(r3).slice(0,400));
console.log("\n=== PriceFeed schema probe ===");
let r4 = await q(PF, `{ __schema { queryType { fields { name } } } }`);
console.log(JSON.stringify(r4?.data?.__schema?.queryType?.fields?.map(f=>f.name)).slice(0,600));
