import puppeteer from "puppeteer-core";
const b = await puppeteer.launch({ executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe", headless: "new", args: ["--no-sandbox"] });
const p = await b.newPage();
await p.setViewport({ width: 1440, height: 1000, deviceScaleFactor: 2 });
const errs = [];
p.on("console", m => { if (m.type() === "error") errs.push(m.text().slice(0,180)); });
p.on("pageerror", e => errs.push("PAGEERROR " + e.message.slice(0,180)));
await p.goto("http://localhost:4173/", { waitUntil: "networkidle2", timeout: 60000 });
await new Promise(r => setTimeout(r, 3000));
await p.screenshot({ path: "../docs/landing-hero.png" });
await p.evaluate(async () => { for (let y=0; y<document.body.scrollHeight; y+=460){ window.scrollTo(0,y); await new Promise(r=>setTimeout(r,80)); } window.scrollTo(0,0); });
await new Promise(r => setTimeout(r, 1200));
await p.screenshot({ path: "../docs/landing.png", fullPage: true });
await p.goto("http://localhost:4173/#/app", { waitUntil: "networkidle2", timeout: 60000 });
await new Promise(r => setTimeout(r, 6000));
await p.screenshot({ path: "../docs/app.png", fullPage: true });
console.log("errors:", errs.slice(0,6).join(" | ") || "none");
await b.close();
